### ISSUE TITLE
第8章 8.4.2 Weather Forecast 部署

### ISSUE THREAD

**Issue by stdec** [cloudnativebooks/cloud-native-istio#12]
第258页
$ kubectl apply -f install/weather-gateway.yaml
文件weather-gateway.yaml, 缺少DestinationRule
@fisherxu

**Comment by x15zhang** [comment]
Done.Thanks!
#15

**Comment by stdec** [comment]
DestinationRule，没有namespace

**Comment by zhanghaipeng404** [comment]
dr没有namespace会导致demo 503。

dr配置需要添加如下ns：

```
namespace: weather
```

**Comment by kafeikejian** [comment]
访问一直返回503

**Comment by x15zhang** [comment]
fixed
