### ISSUE TITLE
unable to recognize "install/weather-v1.yaml": no matches for kind "Deployment" in version "extensions/v1beta2"

### ISSUE THREAD

**Issue by 277631272** [cloudnativebooks/cloud-native-istio#22]
请教下，运行示例时候报错：
k8s version: 1.16.2
kubectl apply -f install/weather-v1.yaml -n weather

unable to recognize "install/weather-v1.yaml": no matches for kind "Deployment" in version "extensions/v1beta2"
unable to recognize "install/weather-v1.yaml": no matches for kind "Deployment" in version "extensions/v1beta2"
unable to recognize "install/weather-v1.yaml": no matches for kind "Deployment" in version "extensions/v1beta2"

**Comment by hzxuzhonghu** [comment]
1.16 `extensions/v1beta2` group version 被删除了， 需要升级使用apps/v1

**Comment by hehehehe123** [comment]
我在windows上用minikube 也遇到同样问题，请问怎么修改，怎么升级使用apps/v1?

**Comment by xujiyou** [comment]
使用 apps/v1 报错：
error: error validating "install/weather-v1.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
