### ISSUE TITLE
kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}

### ISSUE THREAD

**Issue by wangwei0537** [cloudnativebooks/cloud-native-istio#25]
这个命令取不到值

我的loadbalance里边是空的

 kubectl -n istio-system get service istio-ingressgateway -o json
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "creationTimestamp": "2019-11-29T02:39:30Z",
        "labels": {
            "app": "istio-ingressgateway",
            "chart": "gateways",
            "heritage": "Tiller",
            "istio": "ingressgateway",
            "release": "istio"
        },
        "name": "istio-ingressgateway",
        "namespace": "istio-system",
        "resourceVersion": "145750",
        "selfLink": "/api/v1/namespaces/istio-system/services/istio-ingressgateway",
        "uid": "450e4154-d2e2-441f-a8db-6f12ffd7bc41"
    },
    "spec": {
        "clusterIP": "10.111.14.51",
        "externalIPs": [
            "192.168.100.6"
        ],
        "externalTrafficPolicy": "Cluster",
        "ports": [
            {
                "name": "http2",
                "nodePort": 31380,
                "port": 80,
                "protocol": "TCP",
                "targetPort": 80
            },
            {
                "name": "https",
                "nodePort": 31390,
                "port": 443,
                "protocol": "TCP",
                "targetPort": 443
            },
            {
                "name": "tcp",
                "nodePort": 31400,
                "port": 31400,
                "protocol": "TCP",
                "targetPort": 31400
            },
            {
                "name": "https-kiali",
                "nodePort": 31591,
                "port": 15029,
                "protocol": "TCP",
                "targetPort": 15029
            },
            {
                "name": "https-prometheus",
                "nodePort": 32176,
                "port": 15030,
                "protocol": "TCP",
                "targetPort": 15030
            },
            {
                "name": "https-grafana",
                "nodePort": 32174,
                "port": 15031,
                "protocol": "TCP",
                "targetPort": 15031
            },
            {
                "name": "https-tracing",
                "nodePort": 32581,
                "port": 15032,
                "protocol": "TCP",
                "targetPort": 15032
            },
            {
                "name": "tls",
                "nodePort": 30986,
                "port": 15443,
                "protocol": "TCP",
                "targetPort": 15443
            },
            {
                "name": "status-port",
                "nodePort": 31639,
                "port": 15020,
                "protocol": "TCP",
                "targetPort": 15020
            }
        ],
        "selector": {
            "app": "istio-ingressgateway",
            "istio": "ingressgateway",
            "release": "istio"
        },
        "sessionAffinity": "None",
        "type": "LoadBalancer"
    },
    "status": {
        "loadBalancer": {}
    }
}

我添加了外部地址，我想请教一下 哪位大佬可以说说我是哪里搞错了吗 @fisherxu @idouba @liuhewei

**Comment by x15zhang** [comment]
istio-ingressgateway的status是空的，说明绑定外部ip失败，这个命令当然取不到值。
