### ISSUE TITLE
访问控制章节blacklist.yaml报错

### ISSUE THREAD

**Issue by caduke80** [cloudnativebooks/cloud-native-istio#28]
访问控制12.2章节checknothing.spec 为空报错：
```
# kubectl apply -f blacklist.yaml
denier.config.istio.io/denycustomerhandler created
error: error validating "blacklist.yaml": error validating data: unknown object type "nil" in checknothing.spec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by getoutout** [comment]
istio感觉版本间有很大更新，有些比较大的改动，没有向下兼容，我用的istio1.4.3，很多类型都被替换掉了，学低版本，学会了以后也被淘汰了，心累...... 
限流的yaml文件也用不起来，提示 please use "handler" or "instance" instead
黑白名单：
istioctl validate  -f  chapter-files/security/blacklist.yaml 
2020-02-13T02:38:54.097498Z	warn	deprecated Mixer kind "denier", please use "handler" or "instance" instead
2020-02-13T02:38:54.097831Z	warn	deprecated Mixer kind "checknothing", please use "handler" or "instance" instead
Error: 1 error occurred:
	* rule//denycustomer: rule='denycustomer.rule.'.Match: unknown attribute destination.labels
------------------------------------------------------------
istioctl validate  -f  chapter-files/security/whitelist.yaml 
2020-02-13T02:54:02.826517Z	warn	deprecated Mixer kind "listchecker", please use "handler" or "instance" instead
2020-02-13T02:54:02.828131Z	warn	deprecated Mixer kind "listentry", please use "handler" or "instance" instead
Error: 6 errors occurred:
	* listentry//advertisementsource: instance='advertisementsource.listentry.': failed to evaluate expression for field 'Value'; unknown attribute source.labels
	* rule//check: instance='advertisementsource.listentry.': failed to evaluate expression for field 'Value'; unknown attribute source.labels
	* rule//check: rule='check.rule.'.Match: unknown attribute destination.labels
	* rule//check: action='check.rule.[0]': Instance not found: instance='advertisementsource.listentry'
	* rule//check: action='check.rule.[0]': No valid instances found
	* rule//check: rule=check.rule.: No valid actions found in rule

**Comment by hzxuzhonghu** [comment]
Don't worry, most APIs are compatible
