### ISSUE TITLE
使用ratelimiting.yaml配置进行访问次数限制的时候报错

### ISSUE THREAD

**Issue by jansure** [cloudnativebooks/cloud-native-istio#34]
作者朋友您好，我使用cloud-native-istio/chapter-files/traffic-management/ratelimiting.yaml，配置进行访问次数限制的时候报错，如下：
```
Error from server: error when creating "ratelimiting.yaml": admission webhook "validation.istio.io" denied the request: unrecognized type memquota
Error from server: error when creating "ratelimiting.yaml": admission webhook "validation.istio.io" denied the request: unrecognized type quota
```
请帮忙回答一下这个问题是什么引起？我的kubernetes是1.15版本，istio是1.5版本。

@x15zhang @liuhewei @idouba @kevin-wangzefeng @fisherxu

**Comment by hzxuzhonghu** [comment]
Mixer is deprecated, and by default it is not installed in 1.5. Please make sure whether there is a crd named something like this `quotaspecs.config.istio.io`

**Comment by jansure** [comment]
> Mixer is deprecated, and by default it is not installed in 1.5. Please make sure whether there is a crd named something like this `quotaspecs.config.istio.io`

 我的是有quotaspecs.config.istio.io这个CRD的。
￼```
[root@master traffic-management]# kubectl get customresourcedefinition|grep quotaspecs
quotaspecs.config.istio.io                  2019-11-08T06:47:57Z
[root@master traffic-management]# 
```

**Comment by x15zhang** [comment]
The mixer policy is deprecated in Istio 1.5 .
Please consider using [Envoy native rate limiting ](https://www.envoyproxy.io/docs/envoy/v1.13.0/intro/arch_overview/other_features/global_rate_limiting)instead of mixer rate limiting. Istio will add support for native rate limiting API through the Istio extensions API.
