### ISSUE TITLE
第九章 流量监控的9.2调用链路跟踪访问Jaeger界面选择service没有frontend.weather

### ISSUE THREAD

**Issue by dreamflies** [cloudnativebooks/cloud-native-istio#9]
第九章 流量监控的9.2调用链路跟踪访问Jaeger界面选择service没有frontend.weather。
![image](https://user-images.githubusercontent.com/30249088/63918510-68351280-ca6f-11e9-8683-e53066cdd889.png)

**Comment by x15zhang** [comment]
如果遇到调用链信息不能正常获取的情况，看下是不是跟踪取样率没有调整的缘故。 Istio 的跟踪取样率被设置为istio-pilot 的环境变量PILOT_TRACE_SAMPLING，默认值是1，请修改为100。

**Comment by kafeikejian** [comment]
是不是你没访问页面啊？数据没采集到？

**Comment by ZereChen** [comment]
> 如果遇到调用链信息不能正常获取的情况，看下是不是跟踪取样率没有调整的缘故。 Istio 的跟踪取样率被设置为istio-pilot 的环境变量PILOT_TRACE_SAMPLING，默认值是1，请修改为100。

kubectl edit deploy -n istio-system  istio-pilot 将PILOT_TRACE_SAMPLING修改为100
